### PR TITLE
Phi 2 Functionality 😄 

### PR DESCRIPTION
**Pull request by jwafu**
This introduces Phi2 model functionality usage with the Pieces Client to provide an easy way to get started with Phi2 from scratch.

Includes: 
- [x] phi2 GPU example 
- [x] phi2 CPU example 
- [x] additional comments for clarification 
- [x] appending the blog to this repo

### CODE REVIEW

**Review by shivaypiece — APPROVED** [review]
LFG!!

**Comment by shivay-at-pieces** [comment]
image
Although just one thing here, even if I select the Phi-2 model. it still shows response as OpenAI when asking a question to the Copilot. Perhaps the selection isn't working as desired? @jordan-pieces

**Comment by jordan-pieces** [comment]
@shivay-at-pieces ensuring this is working properly today

**Comment by shivaypiece** [comment]
yes working fine now!

**Pull request merged**
